# Generated by Django 5.2.7 on 2025-10-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypartexercise',
            name='body_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.bodypart'),
        ),
        migrations.AlterField(
            model_name='bodypartexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together={('date', 'body_parts', 'exercises')},
        ),
    ]
