# Generated by Django 5.2.7 on 2025-10-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_bodypartexercise_body_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='body_part_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout.bodypartexercise'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together={('date', 'body_part_exercise')},
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='body_parts',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercises',
        ),
    ]
