# Generated by Django 5.2.7 on 2025-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_exercise_description_alter_exercise_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weights',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
