# Generated by Django 5.2.7 on 2025-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_exercise_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
