# Generated by Django 5.2.7 on 2025-10-06 19:37

import workout.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0006_alter_bodypart_description_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", workout.models.UserManager()),
            ],
        ),
    ]
