# Generated by Django 5.2.7 on 2025-10-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0007_alter_user_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workoutsession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workoutsession",
            unique_together={("date", "body_part_exercise", "user")},
        ),
        migrations.DeleteModel(
            name="UserWorkoutSession",
        ),
    ]
