# Generated by Django 5.2.7 on 2025-10-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0008_alter_workoutsession_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workoutsession",
            unique_together={("date", "body_part_exercise")},
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
