# Generated by Django 5.2.7 on 2025-10-08 15:51

import django.db.models.deletion
import workout.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0008_alter_workoutsession_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsession",
            name="user",
            field=models.ForeignKey(
                default=workout.models.WorkoutSession.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
